apiVersion: v1
kind: Service
metadata:
  name: user105-front-service
  namespace: default
spec:
  selector:
    app: user105-front
  ports:
    - protocol: TCP
      port: 80        # 서비스 포트(클러스터 내부)
      targetPort: 80  # 파드(nginx) 컨테이너 포트
  type: ClusterIP     # 외부 노출은 Ingress(ALB)가 담당 → 서비스는 내부 전용