apiVersion: v1
kind: Service
metadata:
  name: user105-front-service
  namespace: default
spec:
  selector:
    app: user105-front
  ports:
    - protocol: TCP
      port: 80        # 로드밸런서가 외부에서 받는 포트
      targetPort: 80  # 파드(nginx) 컨테이너 포트
  type: LoadBalancer  # AWS ELB를 자동 생성해 외부 IP/DNS로 노출